# Generated by Django 5.0.2 on 2026-05-15 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0004_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Prof., Dr., Assoc. Prof.', max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('biography', models.TextField(blank=True, help_text='Short biography')),
                ('avesis_link', models.URLField(blank=True, help_text='Link to Avesis profile', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='professors/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('student_type', models.CharField(choices=[('UG', 'Undergraduate'), ('GR', 'Graduate')], default='GR', max_length=2)),
                ('status', models.CharField(choices=[('current', 'Current'), ('previous', 'Previous')], default='current', max_length=10)),
                ('start_date', models.DateField(help_text='Start date of study')),
                ('end_date', models.DateField(blank=True, help_text='End date (for previous students)', null=True)),
                ('biography', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='sayfalar.professor')),
            ],
            options={
                'ordering': ['-start_date', 'last_name', 'first_name'],
            },
        ),
    ]
