# Generated by Django 5.0.2 on 2026-05-15 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0005_professor_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.RemoveField(
            model_name='student',
            name='biography',
        ),
        migrations.RemoveField(
            model_name='student',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
        migrations.RemoveField(
            model_name='student',
            name='start_date',
        ),
    ]
