# Generated by Django 5.0.2 on 2026-05-15 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0006_alter_student_options_remove_student_biography_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='apply_link',
            field=models.URLField(blank=True, help_text='Link to application form or page', null=True),
        ),
    ]
