# Generated by Django 5.0.2 on 2026-05-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0008_conference_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='principal_investigators',
            field=models.ManyToManyField(blank=True, related_name='pi_projects', to='sayfalar.professor'),
        ),
        migrations.AddField(
            model_name='project',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='projects', to='sayfalar.student'),
        ),
        migrations.AddField(
            model_name='project',
            name='supervisors',
            field=models.ManyToManyField(blank=True, related_name='supervised_projects', to='sayfalar.professor'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='principal_investigators',
            field=models.ManyToManyField(blank=True, related_name='pi_theses', to='sayfalar.professor'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='theses', to='sayfalar.student'),
        ),
        migrations.AddField(
            model_name='thesis',
            name='supervisors',
            field=models.ManyToManyField(blank=True, related_name='supervised_theses', to='sayfalar.professor'),
        ),
    ]
