# Generated by Django 5.0.2 on 2026-05-15 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0009_project_principal_investigators_project_students_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_type',
        ),
    ]
