# Generated by Django 5.0.2 on 2026-05-15 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0010_remove_project_project_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='advisor',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='related_projects',
        ),
        migrations.AddField(
            model_name='topic',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='principal_investigators',
            field=models.ManyToManyField(blank=True, related_name='pi_topics', to='sayfalar.professor'),
        ),
        migrations.AddField(
            model_name='topic',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2026, 5, 15, 18, 4, 7, 900084, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='topics', to='sayfalar.student'),
        ),
        migrations.AddField(
            model_name='topic',
            name='supervisors',
            field=models.ManyToManyField(blank=True, related_name='supervised_topics', to='sayfalar.professor'),
        ),
    ]
