# Generated by Django 5.0.2 on 2026-05-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0011_remove_topic_advisor_remove_topic_related_projects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(choices=[('cms', 'CMS Data Analysis'), ('simulation', 'Simulation Based Data Analysis'), ('ml', 'Machine Learning Based Data Analysis'), ('phenomenology', 'Phenomenological High Energy Physics')], max_length=20)),
                ('description', models.TextField(help_text='Detailed description of the analysis')),
                ('short_description', models.CharField(blank=True, help_text='Brief one-liner for card preview', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='analysis/')),
                ('link', models.URLField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('principal_investigators', models.ManyToManyField(blank=True, related_name='pi_analysis', to='sayfalar.professor')),
                ('students', models.ManyToManyField(blank=True, related_name='analysis_research', to='sayfalar.student')),
                ('supervisors', models.ManyToManyField(blank=True, related_name='supervised_analysis', to='sayfalar.professor')),
            ],
            options={
                'verbose_name_plural': 'Research Analyses',
                'ordering': ['category', 'order', 'title'],
            },
        ),
    ]
