# Generated by Django 5.0.2 on 2026-05-22 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sayfalar', '0012_researchanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True)),
                ('publication_type', models.CharField(choices=[('papers', 'Papers'), ('presentations', 'Presentations'), ('oral', 'Oral Presentations'), ('poster', 'Poster Presentations')], max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('authors', models.TextField(help_text='Authors list, one per line or comma separated')),
                ('description', models.TextField(blank=True, help_text='Abstract or brief description')),
                ('venue', models.CharField(blank=True, help_text='Journal name for Papers, Conference name for Presentations', max_length=300)),
                ('doi', models.CharField(blank=True, help_text='DOI number', max_length=100)),
                ('link', models.URLField(blank=True, help_text='Link to paper, PDF, or event', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='publications/')),
                ('event_date', models.DateField(blank=True, help_text='For presentations', null=True)),
                ('event_location', models.CharField(blank=True, help_text='For presentations', max_length=300)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='sayfalar.professor')),
            ],
            options={
                'verbose_name_plural': 'Publications',
                'ordering': ['-year', '-created_at'],
            },
        ),
    ]
