# Generated by Django 6.0.6 on 2026-06-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sayfalar", "0013_publication"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="department",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Department"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="grade",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Grade/Year"
            ),
        ),
    ]
