# Generated by Django 6.0.6 on 2026-07-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sayfalar", "0014_student_department_student_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="institution",
            field=models.CharField(
                blank=True,
                help_text="e.g. TÜBİTAK, BAP, CERN",
                max_length=100,
                verbose_name="Institution/Funding Tag",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="project_level",
            field=models.CharField(
                choices=[("PHD", "PhD Level"), ("UG", "Undergrad Level")],
                default="PHD",
                max_length=10,
                verbose_name="Project Level",
            ),
        ),
    ]
