# Generated by Django 6.0.6 on 2026-07-01 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sayfalar", "0015_project_institution_project_project_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="participants",
        ),
        migrations.DeleteModel(
            name="ProjectParticipation",
        ),
    ]
