# Generated by Django 6.0.6 on 2026-07-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sayfalar", "0016_remove_project_participants_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="activities/"),
                ),
                ("description", models.TextField()),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated tags (e.g. deeplearning, physics, presentation)",
                        max_length=200,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("workshop", "Workshop"),
                            ("seminar", "Seminar"),
                            ("social", "Social Event"),
                            ("outreach", "Outreach/News"),
                            ("meeting", "Lab Meeting"),
                        ],
                        default="outreach",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "link",
                    models.URLField(
                        blank=True, help_text="Optional external link", null=True
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "principal_investigators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="pi_activities",
                        to="sayfalar.professor",
                    ),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        blank=True, related_name="activities", to="sayfalar.student"
                    ),
                ),
                (
                    "supervisors",
                    models.ManyToManyField(
                        blank=True,
                        related_name="supervised_activities",
                        to="sayfalar.professor",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Activities",
                "ordering": ["-start_date", "title"],
            },
        ),
    ]
