# Generated by Django 6.0.6 on 2026-07-01 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sayfalar", "0017_activity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="principal_investigators",
        ),
        migrations.CreateModel(
            name="ActivityImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="activities/gallery/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="sayfalar.activity",
                    ),
                ),
            ],
        ),
    ]
