# Generated by Django 6.0.6 on 2026-07-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sayfalar", "0018_remove_activity_principal_investigators_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="pre_description",
            field=models.TextField(
                blank=True, help_text="Brief summary/preview for the card list"
            ),
        ),
    ]
