# Generated by Django 6.0.6 on 2026-07-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sayfalar", "0019_activity_pre_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when the announcement expires.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="nonstop",
            field=models.BooleanField(
                default=False, help_text="If True, the announcement will never expire."
            ),
        ),
    ]
