# Generated by Django 6.0.6 on 2026-07-01 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sayfalar", "0020_announcement_expires_at_announcement_nonstop"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Detailed description/content for the announcement detail page.",
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="slug",
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.CreateModel(
            name="AnnouncementLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="Label for the link, e.g. 'Register Here'",
                        max_length=100,
                    ),
                ),
                ("url", models.URLField(help_text="URL of the link")),
                (
                    "announcement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_links",
                        to="sayfalar.announcement",
                    ),
                ),
            ],
        ),
    ]
