# Generated by Django 6.0.6 on 2026-07-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sayfalar", "0021_announcement_description_announcement_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Optional photo/image for the position",
                null=True,
                upload_to="positions/",
            ),
        ),
    ]
