# Generated by Django 6.0.6 on 2026-07-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sayfalar", "0022_position_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="link_label",
            field=models.CharField(
                blank=True,
                help_text="Custom label for the main link, e.g. 'Register Here'",
                max_length=100,
            ),
        ),
    ]
